<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLR2T2WSF035" name="Test(failed)" tests="14" failures="13" timestamp="29 Oct 2018 12:32:30 GMT" time="665.277" errors="0">
  <testcase name="verify_ErrorCategoryReport_Historical" time="72.483" classname="historicalReports.ErrorCategory">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-036] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-036] not found</b> expected [true] but found [false]
	at historicalReports.ErrorCategory.verify_ErrorCategoryReport_Historical(ErrorCategory.java:176)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_ErrorCategoryReport_Historical -->
  <testcase name="verify_ClientEscalation" time="38.095" classname="transaction.ClientEscalation">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;Account [20181029-037] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>Account [20181029-037] not found</b> expected [true] but found [false]
	at transaction.ClientEscalation.verify_ClientEscalation(ClientEscalation.java:130)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_ClientEscalation -->
  <testcase name="submit_QCAudit_AcceptFeedBack" time="54.93" classname="qc.AcceptFeedback">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-038] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-038] not found</b> expected [true] but found [false]
	at qc.AcceptFeedback.audit_QC(AcceptFeedback.java:218)
	at qc.AcceptFeedback.submit_QCAudit_AcceptFeedBack(AcceptFeedback.java:124)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- submit_QCAudit_AcceptFeedBack -->
  <testcase name="verify_WorkOrderSummary_In_CodingInbox" time="28.849" classname="inbox.WorkOrderSummaryResponse"/>
  <testcase name="verify_Coding" time="37.697" classname="transaction.Coding">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-039] not found in Coding inbox&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-039] not found in Coding inbox</b> expected [true] but found [false]
	at transaction.Coding.verify_Coding(Coding.java:136)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_Coding -->
  <testcase name="verify_Trasnsaction_History" time="38.334" classname="transaction.Transaction_History">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;Account [20181029-040] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>Account [20181029-040] not found</b> expected [true] but found [false]
	at transaction.Transaction_History.verify_Trasnsaction_History(Transaction_History.java:144)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_Trasnsaction_History -->
  <testcase name="verify_RebuttalReview_Accept" time="41.797" classname="qc.Rebuttal_Review">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-041] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-041] not found</b> expected [true] but found [false]
	at qc.Rebuttal_Review.audit_QC(Rebuttal_Review.java:278)
	at qc.Rebuttal_Review.verify_RebuttalReview_Accept(Rebuttal_Review.java:121)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_RebuttalReview_Accept -->
  <testcase name="verify_VoiceCall" time="42.308" classname="transaction.VoiceCall">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;Patient Account [20181029-042] found at VOICE_CALL&amp;lt;/b&amp;gt; expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: <b>Patient Account [20181029-042] found at VOICE_CALL</b> expected [false] but found [true]
	at transaction.VoiceCall.verify_VoiceCall(VoiceCall.java:141)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_VoiceCall -->
  <testcase name="verify_SimpleQuality_Report" time="73.639" classname="historicalReports.SimpleQuality">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-043] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-043] not found</b> expected [true] but found [false]
	at historicalReports.SimpleQuality.verify_SimpleQuality_Report(SimpleQuality.java:207)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_SimpleQuality_Report -->
  <testcase name="verify_QCWorkedAccounts_Report" time="42.401" classname="historicalReports.QCWorkedAccounts">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-047] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-047] not found</b> expected [true] but found [false]
	at historicalReports.QCWorkedAccounts.verify_QCWorkedAccounts_Report(QCWorkedAccounts.java:135)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_QCWorkedAccounts_Report -->
  <testcase name="verify_ProviderCredential_Dashboard" time="85.162" classname="dashboard.ProviderCredential">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [1] but found [0]
	at dashboard.ProviderCredential.verify_ProviderCredential_Dashboard(ProviderCredential.java:163)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- verify_ProviderCredential_Dashboard -->
  <testcase name="verify_Denail" time="36.896" classname="transaction.Denial">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;Account [20181029-054] not found&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>Account [20181029-054] not found</b> expected [true] but found [false]
	at transaction.Denial.verify_Denail(Denial.java:149)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_Denail -->
  <testcase name="verify_QCHistory" time="33.76" classname="qc.QC_History">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;UID [20181029-049] not found in Coding inbox&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>UID [20181029-049] not found in Coding inbox</b> expected [true] but found [false]
	at qc.QC_History.verify_QCHistory(QC_History.java:137)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_QCHistory -->
  <testcase name="verify_Credentialing" time="14.759" classname="transaction.Credentialing">
    <failure type="java.lang.AssertionError" message="&amp;lt;b&amp;gt;No data available in table&amp;lt;/b&amp;gt; expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: <b>No data available in table</b> expected [true] but found [false]
	at transaction.Credentialing.verify_Credentialing(Credentialing.java:84)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_Credentialing -->
</testsuite> <!-- Test(failed) -->
