<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="BLR2T2WSF035" name="analyst.WorkOrderSummary" tests="3" failures="3" timestamp="3 Apr 2018 13:32:10 GMT" time="935.743" errors="0">
  <testcase name="verify_WorkOrderSummary_In_Analyst_Role" time="334.007" classname="analyst.WorkOrderSummary">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&lt;br&gt;Number of accounts in &lt;b&gt;REGLAR&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [0] but found [1177],
	&lt;br&gt;Number of accounts in &lt;b&gt;CODING RESPONSE&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [15] but found [16],
	&lt;br&gt;Number of accounts in &lt;b&gt;REGLAR&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[WES]&lt;/b&gt;,  expected [5] but found [3],
	&lt;br&gt;Number of accounts in &lt;b&gt;CODING RESPONSE&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[WES]&lt;/b&gt;,  expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	<br>Number of accounts in <b>REGLAR</b> queue don't match for practice <b>[HCR]</b>,  expected [0] but found [1177],
	<br>Number of accounts in <b>CODING RESPONSE</b> queue don't match for practice <b>[HCR]</b>,  expected [15] but found [16],
	<br>Number of accounts in <b>REGLAR</b> queue don't match for practice <b>[WES]</b>,  expected [5] but found [3],
	<br>Number of accounts in <b>CODING RESPONSE</b> queue don't match for practice <b>[WES]</b>,  expected [0] but found [1]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at analyst.WorkOrderSummary.verify_WorkOrderSummary_In_Analyst_Role(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_WorkOrderSummary_In_Analyst_Role -->
  <testcase name="verify_WorkOrderSummary_In_Manager_Role" time="403.817" classname="analyst.WorkOrderSummary">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&lt;br&gt;Number of accounts in &lt;b&gt;REGLAR&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [0] but found [1177],
	&lt;br&gt;Number of accounts in &lt;b&gt;CODING RESPONSE&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [3] but found [4],
	&lt;br&gt;Number of accounts in &lt;b&gt;REGLAR&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[WES]&lt;/b&gt;,  expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	<br>Number of accounts in <b>REGLAR</b> queue don't match for practice <b>[HCR]</b>,  expected [0] but found [1177],
	<br>Number of accounts in <b>CODING RESPONSE</b> queue don't match for practice <b>[HCR]</b>,  expected [3] but found [4],
	<br>Number of accounts in <b>REGLAR</b> queue don't match for practice <b>[WES]</b>,  expected [5] but found [3]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at analyst.WorkOrderSummary.verify_WorkOrderSummary_In_Manager_Role(WorkOrderSummary.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_WorkOrderSummary_In_Manager_Role -->
  <testcase name="verify_WorkOrderSummary_In_TL_Role" time="197.919" classname="analyst.WorkOrderSummary">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	&lt;br&gt;Number of accounts in &lt;b&gt;REGLAR&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [0] but found [1177],
	&lt;br&gt;Number of accounts in &lt;b&gt;CODING RESPONSE&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [3] but found [4],
	&lt;br&gt;Number of accounts in &lt;b&gt;PAYMENT RESPONSE&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[HCR]&lt;/b&gt;,  expected [1] but found [0],
	&lt;br&gt;Number of accounts in &lt;b&gt;REGLAR&lt;/b&gt; queue don&#039;t match for practice &lt;b&gt;[WES]&lt;/b&gt;,  expected [5] but found [3]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	<br>Number of accounts in <b>REGLAR</b> queue don't match for practice <b>[HCR]</b>,  expected [0] but found [1177],
	<br>Number of accounts in <b>CODING RESPONSE</b> queue don't match for practice <b>[HCR]</b>,  expected [3] but found [4],
	<br>Number of accounts in <b>PAYMENT RESPONSE</b> queue don't match for practice <b>[HCR]</b>,  expected [1] but found [0],
	<br>Number of accounts in <b>REGLAR</b> queue don't match for practice <b>[WES]</b>,  expected [5] but found [3]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at analyst.WorkOrderSummary.verify_WorkOrderSummary_In_TL_Role(WorkOrderSummary.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_WorkOrderSummary_In_TL_Role -->
</testsuite> <!-- analyst.WorkOrderSummary -->
